---
- name: Provision production machine
  hosts: localhost
  roles:
  - kewlfft.aur

  tasks:

    - name: Create user
      become: yes
      user:
        name: aur_builder
        group: wheel

    - name: Change sudoers.
      become: yes
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        validate: "visudo -cf %s"

    - name: Install packages
      become: yes
      become_user: aur_builder
      aur:
        name: "{{ item }}"
        use: yay
        extra_args: --overwrite "*"
      loop: "{{ lookup('file', 'ref/pkglistaur.txt').splitlines()}}"


    - name: Turn on systemd services.
      systemd:
        name: "{{ item }}"
        state: started
        scope: system # Default
      loop: "{{ lookup('file', 'ref/systemdlist.txt').splitlines()}}"

    - name: Turn on systemd user services.
      systemd:
        name: "{{ item }}"
        state: started
        scope: user
      loop: "{{ lookup('file', 'ref/systemduserlist.txt').splitlines()}}"



    #- name: Set up remote server
      #tags: debug
      #block:
        #- name: Clone dotfiles repository
          #git:
            #repo: https://github.com/Yann21/dotfiles.git
            #dest: ~/dotfiles_test

        #- name: Install dotfiles to user directory
          #shell: rcup -v

        #- name: TODO - Install vim plugins

    #- name: Fresh install
      #tags: debug
      #block:
        #- name: Install XMonad, XMobar
